
stages:
  - 'One'

image:
    name: 'wodby/drupal-php:7.1-4.4.2'

all_in_one:
    stage: 'One'
    tags:
        - 'docker-staging'
    services:
        -
            name: 'ttonyh/chrome-headless-stable:1.11.0'
            alias: 'chromium'
    script:
        - 'export APP_HTTP_HOSTNAME="${HOSTNAME}"'
        - 'export APP_HTTP_HOSTNAME_PORT="${APP_HTTP_HOSTNAME}:8888"'
        - 'export APP_CHROMIUM_HOSTNAME_PORT="chromium:9222"'
        - 'export DRUSH_OPTIONS_URI="http://${APP_HTTP_HOSTNAME_PORT}"'
        - 'export DRUSH_OPTIONS_ROOT="${PWD}/docroot"'
        - 'composer install'
        - 'composer run lint'
        - 'composer run drupal:install'
        - 'cd docroot && (php -S "${APP_HTTP_HOSTNAME_PORT}" .ht.router.php &) && cd ..'
        - 'bin/drush status'
        - 'curl "${DRUSH_OPTIONS_URI}" -I'
        - 'echo ${APP_CHROMIUM_HOSTNAME_PORT}'
        - 'curl "http://${APP_CHROMIUM_HOSTNAME_PORT}/json/version" -v --fail'
        - 'composer run test'
    artifacts:
        name: '${CI_JOB_NAME}_${CI_COMMIT_REF_NAME}'
        when: 'always'
        paths:
          - 'reports'
        expire_in: '1 hour'
